#!/usr/bin/env python3
"""
Pixel-grid source of truth for the About-box mascot sprite, mirroring how
the app's five file-type icons are built (small hand-authored pixel grid ->
emitted SVG). Unlike those icons, which had to be hand-transcribed into
icons.js after the fact, this script writes src/js/sprite.js directly, so
there's no separate manual transcription step to keep in sync.

Original chibi-style character, loosely in the vein of small pixel-art
bartender/VTuber sprites referenced when this was commissioned -- NOT a
redraw of any specific one: this script's own hand-authored pixel grid,
palette values chosen to sit in the same general family (deep violet
twin-tails, pale skin, white collar, dark skirt) without matching any
reference image's exact hex values. This, along with the boot chime, is one
of exactly two documented exceptions to the app's strict 1-bit rule -- see
the header comment in src/css/system7.css and CLAUDE.md's "De-branding &
1-bit" bullet. Confined to the About modal; never reaches the main window
chrome.

Run: python3 sprite/build_sprite.py
"""

import os

WIDTH = 28
HEIGHT = 26
HALF_WIDTH = WIDTH // 2  # 14

# Each row is defined as its LEFT half only (columns 0-13); column 13 is the
# row's center-most pixel before mirroring. The right half is generated by
# mirroring, guaranteeing a perfectly symmetric front-facing silhouette with
# no hand-counted-pixel risk — including the twin-tails, which (unlike the
# previous single-ponytail design) are naturally symmetric and need no
# asymmetric post-mirror overrides at all.
#
# Columns 0-3ish carry the tail on rows where it's present, floating outside
# the head/body silhouette that occupies the rest of the row (a real gap —
# see row 9 — rather than the tail fusing into the jawline).
#
# Palette:
#   H hair          S skin
#   E eye (class-tagged for the CSS blink)   K blush
#   W collar/shirt  T tie/bow   O skirt/vest   B boots
HALF_ROWS = [
    ".......HHHHHHH",  # 0  hair dome top
    "......HHHHHHHH",  # 1
    ".....HHHHHHHHH",  # 2
    "....HHHHHHHHHH",  # 3  full hair band
    "..HHHHHHHHSSSS",  # 4  tail root merges with head hair; face begins
    "..HHHHHHHSSSSS",  # 5
    "..HHHHHHHSEESS",  # 6  eye, top half — placed near center (idx10-11)
    "..HHHHHHHSEESS",  # 7  eye, bottom half — so the mirror joins into ONE
    "..HHHHHKKSSSSS",  # 8  blush — placed away from center so it mirrors
    "..HHHHSSSSSSSS",  # 9  into TWO separate cheek patches, not one bar
    "..HH.SSSSSSSSS",  # 10 jaw; tail floats free of it (real gap at idx4)
    "..HH....SSSSSS",  # 11 neck — narrower than the jaw above on purpose
    "HH.WWWWWWWWTTT",  # 12 shoulders widen back out; bow at idx11-13 sits
                        #    AT the mirror seam so it joins into one shape,
                        #    not two floating marks either side of center
    "HH.OOWWWWWWWWW",  # 13
    "HH.OOWWWWWWWWW",  # 14
    "HH.SOWWWWWWWWW",  # 15 hand peeking out of sleeve
    "HH.SOWWWWWWWWW",  # 16
    "...OOOOOOOOOOO",  # 17 waist; tail has already tapered out
    "...OOOOOOOOOOO",  # 18
    "..OOOOOOOOOOOO",  # 19 skirt flare
    ".OOOOOOOOOOOOO",  # 20 hem
    ".OOOOOOOOOOOOO",  # 21
    "...........SSS",  # 22 bare legs, centered
    "...........SSS",  # 23
    "...........BBB",  # 24 boots
    "...........BBB",  # 25
]

PALETTE = {
    "H": "#4a2f6b",
    "S": "#fbe0cc",
    "E": "#2a1018",
    "K": "#f0a8a8",
    "W": "#f7f3ec",
    "T": "#7a1228",
    "O": "#221a33",
    "B": "#14111a",
}


def build_grid():
    grid = []
    for i, half in enumerate(HALF_ROWS):
        assert len(half) == HALF_WIDTH, f"row {i}: half-row must be {HALF_WIDTH} chars, got {len(half)}: {half!r}"
        grid.append(list(half + half[::-1]))
    assert len(grid) == HEIGHT, f"expected {HEIGHT} rows, got {len(grid)}"
    return grid


def svg_for(grid):
    rects = []
    for y, row in enumerate(grid):
        for x, ch in enumerate(row):
            if ch == ".":
                continue
            color = PALETTE[ch]
            cls = ' class="sprite-eye"' if ch == "E" else ""
            rects.append(f'<rect x="{x}" y="{y}" width="1" height="1" fill="{color}"{cls}/>')
    body = "".join(rects)
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" '
        f'shape-rendering="crispEdges" role="img" aria-label="mascot">{body}</svg>'
    )


def main():
    svg = svg_for(build_grid())
    out_path = os.path.join(os.path.dirname(__file__), "..", "src", "js", "sprite.js")
    out_path = os.path.normpath(out_path)

    js = (
        "// Generated by sprite/build_sprite.py — do not hand-edit.\n"
        "// Original chibi mascot for the About box. One of exactly two documented\n"
        "// exceptions to the app's strict 1-bit rule (the other is the boot splash's\n"
        "// chromatic-aberration glitch) — see system7.css's header comment and\n"
        "// CLAUDE.md's \"De-branding & 1-bit\" bullet. Confined to #about-modal.\n"
        f"const SYS7_MASCOT_SVG = `{svg}`;\n"
    )

    with open(out_path, "w") as f:
        f.write(js)
    print(f"wrote {out_path} ({len(svg)} bytes of SVG, {WIDTH}x{HEIGHT})")


if __name__ == "__main__":
    main()
