#!/usr/bin/env python3
"""
Pixel-grid source of truth for the About-box mascot sprite, mirroring how
the app's five file-type icons are built (small hand-authored pixel grid ->
emitted SVG). Unlike those icons, which had to be hand-transcribed into
icons.js after the fact, this script writes src/js/sprite.js directly, so
there's no separate manual transcription step to keep in sync.

Original chibi-style character, loosely in the vein of the small pixel-art
bartender sprites referenced when this was commissioned -- NOT a redraw of
any specific one: different hairstyle silhouette (single ponytail, not
double pigtails), different outfit (a vest/apron nod to "cleaning utility"
as much as "bartender"), and a palette that doesn't match any reference
image's hex values. This, along with the boot chime, is one of exactly two
documented exceptions to the app's strict 1-bit rule -- see the header
comment in src/css/system7.css and CLAUDE.md's "De-branding & 1-bit" bullet.
Confined to the About modal; never reaches the main window chrome.

Run: python3 sprite/build_sprite.py
"""

import os

WIDTH = 16
HEIGHT = 22

# Each row is defined as its LEFT half only (columns 0-7); column 7 is the
# row's center-most pixel before mirroring. The right half (columns 8-15) is
# generated by mirroring, guaranteeing a perfectly symmetric front-facing
# silhouette with no hand-counted-pixel risk. Asymmetric details (the
# ponytail) are applied afterward, as overrides on the right side only.
#
# Palette:
#   H hair (base)      h hair (highlight)   S skin
#   E eye (class-tagged for the CSS blink)  O outfit/vest
#   A apron/bib accent  B boots
HALF_ROWS = [
    "....HHHH",  # 0  hairline peak
    "...HHHHH",  # 1
    "..HHHHHH",  # 2
    ".HHHHHHH",  # 3  full hair band
    ".HSSSSSS",  # 4  bangs recede, face begins
    ".HSSSSSS",  # 5
    ".HSSSSES",  # 6  eye
    ".HSSSSSS",  # 7
    ".HHSSSSS",  # 8  jaw, sideburn
    "..HSSSSS",  # 9  chin/neck
    "..OOOOAA",  # 10 collar, apron bib starts
    "OOOOOOAA",  # 11 shoulders/arms
    "OOOOOOAA",  # 12
    "SOOOOOAA",  # 13 hand peeking out of sleeve
    "SOOOOOAA",  # 14
    ".OOOOOAA",  # 15 waist narrows, arm rejoins body
    "..OOOOAA",  # 16
    "..OOOOOO",  # 17 skirt hem, apron ends
    "...SSSSS",  # 18 bare legs
    "...SSSSS",  # 19
    "...BBBBB",  # 20 boots
    "...BBBBB",  # 21
]

PALETTE = {
    "H": "#7a1228",
    "h": "#a8324f",
    "S": "#f2c9a1",
    "E": "#241017",
    "O": "#33323d",
    "A": "#f5efe6",
    "B": "#1a1a1a",
}

# Ponytail: a hanging strand on the right side only, outside the mirrored
# hair mass, applied after mirroring. (row, col, char) — col is in the final
# 0-15 space, not the half-row space.
PONYTAIL = [
    (2, 12, "H"), (2, 13, "h"),
    (3, 12, "H"), (3, 13, "H"), (3, 14, "h"),
    (4, 12, "H"), (4, 13, "H"), (4, 14, "H"),
    (5, 13, "H"), (5, 14, "H"),
    (6, 13, "H"), (6, 14, "H"),
    (7, 13, "H"), (7, 14, "h"),
    (8, 13, "H"),
    (9, 13, "H"),
    (10, 13, "H"),
    (11, 13, "H"),
    (12, 13, "h"),
    (13, 13, "H"),
]


def build_grid():
    grid = []
    for half in HALF_ROWS:
        assert len(half) == WIDTH // 2, f"half-row must be {WIDTH // 2} chars: {half!r}"
        full = half + half[::-1]
        grid.append(list(full))
    assert len(grid) == HEIGHT

    for row, col, ch in PONYTAIL:
        grid[row][col] = ch

    return grid


def svg_for(grid):
    rects = []
    for y, row in enumerate(grid):
        for x, ch in enumerate(row):
            if ch == ".":
                continue
            color = PALETTE[ch]
            cls = ' class="sprite-eye"' if ch == "E" else ""
            rects.append(f'<rect x="{x}" y="{y}" width="1" height="1" fill="{color}"{cls}/>')
    body = "".join(rects)
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" '
        f'shape-rendering="crispEdges" role="img" aria-label="mascot">{body}</svg>'
    )


def main():
    svg = svg_for(build_grid())
    out_path = os.path.join(os.path.dirname(__file__), "..", "src", "js", "sprite.js")
    out_path = os.path.normpath(out_path)

    js = (
        "// Generated by sprite/build_sprite.py — do not hand-edit.\n"
        "// Original chibi mascot for the About box. One of exactly two documented\n"
        "// exceptions to the app's strict 1-bit rule (the other is the boot splash's\n"
        "// chromatic-aberration glitch) — see system7.css's header comment and\n"
        "// CLAUDE.md's \"De-branding & 1-bit\" bullet. Confined to #about-modal.\n"
        f"const SYS7_MASCOT_SVG = `{svg}`;\n"
    )

    with open(out_path, "w") as f:
        f.write(js)
    print(f"wrote {out_path} ({len(svg)} bytes of SVG)")


if __name__ == "__main__":
    main()
